[tool.ruff]
line-length = 88
target-version = "py310"
exclude = [
    ".venv",
    "data",
    "notebooks",
    "configs",
    "dvc-sa.json",
]
src = ["src", "scripts"]
extend-select = ["I", "D"]  # I = isort (импорты), D = docstrings

[tool.ruff.format]
quote-style = "double"

[tool.black]
line-length = 88
target-version = ["py310"]
exclude = '''
(
  /(
    \.venv|
    data|
    notebooks|
    configs
  )/
)
'''

[tool.mypy]
python_version = 3.10
ignore_missing_imports = true
disallow_untyped_defs = true
strict_optional = true
files = ["src", "scripts"]
exclude = '(data|notebooks|configs)'
